DROP SEQUENCE "TAMOA"."ART_MEDIUM_ID_SEQ";
DROP SEQUENCE "TAMOA"."ARTIST_ID_SEQ";
DROP SEQUENCE "TAMOA"."ARTWORK_ID_SEQ";
DROP SEQUENCE "TAMOA"."BANK_ID_SEQ";
DROP SEQUENCE "TAMOA"."CITY_ID_SEQ";
DROP SEQUENCE "TAMOA"."COLLECTION_ID_SEQ";
DROP SEQUENCE "TAMOA"."KLIENT_ID_SEQ";
DROP SEQUENCE "TAMOA"."TRANSACTION_ID_SEQ";
