/* BANK - Artist - Collection - Medium - Artwork -  Sale_Trans_det - Sale_Trans - City - Client*/

INSERT INTO "TAMOA"."BANK" (BANK_CODE, BANK_NAME) VALUES ('14000', 'Capitect Bank');
INSERT INTO "TAMOA"."BANK" (BANK_CODE, BANK_NAME) VALUES (BANK_ID_SEQ.nextval, 'Standard Bank');
INSERT INTO "TAMOA"."BANK" (BANK_CODE, BANK_NAME) VALUES (BANK_ID_SEQ.nextval, 'First National Bank');
INSERT INTO "TAMOA"."BANK" (BANK_CODE, BANK_NAME) VALUES (BANK_ID_SEQ.nextval, 'Swiss International');
INSERT INTO "TAMOA"."BANK" (BANK_CODE, BANK_NAME) VALUES (BANK_ID_SEQ.nextval, 'Caymin Islands Bank');
INSERT INTO "TAMOA"."BANK" (BANK_CODE, BANK_NAME) VALUES (BANK_ID_SEQ.nextval, 'African Bank');
INSERT INTO "TAMOA"."BANK" (BANK_CODE, BANK_NAME) VALUES (BANK_ID_SEQ.nextval, 'Bank of America');


INSERT INTO "TAMOA"."ARTIST" (ARTIST_ID, BANK_CODE, ARTIST_INITS, ARTIST_LNAME, ARTIST_RSA_ID, ARTIST_CELL, ARTIST_EMAIL, 
    ARTIST_ACCOUNT_NO, ARTIST_DOB) VALUES ('1', '14000', 'P', 'Parker', '9802225117085', '27864853203', 
    'peter.parker@spiderman.com', '2486152535', TO_DATE('1998-02-22', 'YYYY-MM-DD'));
INSERT INTO "TAMOA"."ARTIST" (ARTIST_ID, BANK_CODE, ARTIST_INITS, ARTIST_LNAME, ARTIST_RSA_ID, ARTIST_CELL, ARTIST_EMAIL, 
    ARTIST_ACCOUNT_NO, ARTIST_DOB) VALUES (ARTIST_ID_SEQ.nextval, '14003', 'RJ', 'Steele', '8811185117080', '27864853203', 
    'steel.rhino@gmail.com', '2486152535', TO_DATE('1988-11-18', 'YYYY-MM-DD'));
INSERT INTO "TAMOA"."ARTIST" (ARTIST_ID, BANK_CODE, ARTIST_INITS, ARTIST_LNAME, ARTIST_RSA_ID, ARTIST_CELL, ARTIST_EMAIL, 
    ARTIST_ACCOUNT_NO, ARTIST_DOB) VALUES (ARTIST_ID_SEQ.nextval, '14004', 'M', 'Eros', '7401083113030', '27631840320', 
    'erosM@yahoomail.com', '2486152535', TO_DATE('1974-01-08', 'YYYY-MM-DD'));
INSERT INTO "TAMOA"."ARTIST" (ARTIST_ID, BANK_CODE, ARTIST_INITS, ARTIST_LNAME, ARTIST_RSA_ID, ARTIST_CELL, ARTIST_EMAIL, 
    ARTIST_ACCOUNT_NO, ARTIST_DOB) VALUES (ARTIST_ID_SEQ.nextval, '14006', 'L', 'Laas', '6105305117085', '27846274141', 
    'LL.laas@kantilla.com', '2486152535', TO_DATE('1961-05-30', 'YYYY-MM-DD'));
INSERT INTO "TAMOA"."ARTIST" (ARTIST_ID, BANK_CODE, ARTIST_INITS, ARTIST_LNAME, ARTIST_RSA_ID, ARTIST_CELL, ARTIST_EMAIL, 
    ARTIST_ACCOUNT_NO, ARTIST_DOB) VALUES (ARTIST_ID_SEQ.nextval, '14002', 'E', 'Cent', '6601135117085', '27876489595', 
    '50cent.EC@wraps.com', '2486152535', TO_DATE('1966-01-13', 'YYYY-MM-DD'));
INSERT INTO "TAMOA"."ARTIST" (ARTIST_ID, BANK_CODE, ARTIST_INITS, ARTIST_LNAME, ARTIST_RSA_ID, ARTIST_CELL, ARTIST_EMAIL, 
    ARTIST_ACCOUNT_NO, ARTIST_DOB) VALUES (ARTIST_ID_SEQ.nextval, '14001', 'Q', 'Poole', '9005055117085', '27626896113', 
    'pooleQ@hippo.com', '2486152535', TO_DATE('1990-05-05', 'YYYY-MM-DD'));


INSERT INTO "TAMOA"."COLLECTION" (COLLECTION_ID, ARTIST_ID, COLLECTION_NAME) VALUES ('1000', '2', 'Halogen Records');
INSERT INTO "TAMOA"."COLLECTION" (COLLECTION_ID, ARTIST_ID, COLLECTION_NAME) VALUES 
    (COLLECTION_ID_SEQ.nextval, '5', 'The Amusing Pea');
INSERT INTO "TAMOA"."COLLECTION" (COLLECTION_ID, ARTIST_ID, COLLECTION_NAME) VALUES 
    (COLLECTION_ID_SEQ.nextval, '4', 'Master Suite');
INSERT INTO "TAMOA"."COLLECTION" (COLLECTION_ID, ARTIST_ID, COLLECTION_NAME) VALUES 
    (COLLECTION_ID_SEQ.nextval, '1', 'Docking');
INSERT INTO "TAMOA"."COLLECTION" (COLLECTION_ID, ARTIST_ID, COLLECTION_NAME) VALUES 
    (COLLECTION_ID_SEQ.nextval, '5', 'Culture Shock');


INSERT INTO "TAMOA"."ART_MEDIUM" (MEDIUM_CODE, MEDIUM_DESCRIPTION) VALUES ('4000', 'Stone Carving');
INSERT INTO "TAMOA"."ART_MEDIUM" (MEDIUM_CODE, MEDIUM_DESCRIPTION) VALUES (ART_MEDIUM_ID_SEQ.nextval, 'Wood Print');
INSERT INTO "TAMOA"."ART_MEDIUM" (MEDIUM_CODE, MEDIUM_DESCRIPTION) VALUES (ART_MEDIUM_ID_SEQ.nextval, 'Painting');
INSERT INTO "TAMOA"."ART_MEDIUM" (MEDIUM_CODE, MEDIUM_DESCRIPTION) VALUES (ART_MEDIUM_ID_SEQ.nextval, 'Ink Print');
INSERT INTO "TAMOA"."ART_MEDIUM" (MEDIUM_CODE, MEDIUM_DESCRIPTION) VALUES (ART_MEDIUM_ID_SEQ.nextval, 'Glass Sculpture');


INSERT INTO "TAMOA"."ARTWORK" (ARTWORK_ID, COLLECTION_ID, MEDIUM_CODE, ARTWORK_TITLE, ARTWORK_DOC, LENGTH_CM, WIDTH_CM, 
    ART_STATUS, ART_ESTIMATED_VALUE) VALUES ('2000', '1003', '4002', 'A Painting of Hal', 
    TO_DATE('1999-06-08', 'YYYY-MM-DD'), '200', '60', 'For Sale', '20000');
INSERT INTO "TAMOA"."ARTWORK" (ARTWORK_ID, COLLECTION_ID, MEDIUM_CODE, ARTWORK_TITLE, ARTWORK_DOC, LENGTH_CM, WIDTH_CM, 
    ART_STATUS, ART_ESTIMATED_VALUE) VALUES (ARTWORK_ID_SEQ.nextval, '1004', '4000', 'Eloquence', 
    TO_DATE('1958-11-08', 'YYYY-MM-DD'), '100', '30', 'For Sale', '40000');
INSERT INTO "TAMOA"."ARTWORK" (ARTWORK_ID, COLLECTION_ID, MEDIUM_CODE, ARTWORK_TITLE, ARTWORK_DOC, LENGTH_CM, WIDTH_CM, 
    ART_STATUS, ART_ESTIMATED_VALUE) VALUES (ARTWORK_ID_SEQ.nextval, '1001', '4004', 'Beast', 
    TO_DATE('2007-03-20', 'YYYY-MM-DD'), '40', '500', 'For Sale', '65000');
INSERT INTO "TAMOA"."ARTWORK" (ARTWORK_ID, COLLECTION_ID, MEDIUM_CODE, ARTWORK_TITLE, ARTWORK_DOC, LENGTH_CM, WIDTH_CM, 
    ART_STATUS, ART_ESTIMATED_VALUE) VALUES (ARTWORK_ID_SEQ.nextval, '1000', '4001', 'Forward 1', 
    TO_DATE('2010-01-30', 'YYYY-MM-DD'), '3', '880', 'For Sale', '3500');
INSERT INTO "TAMOA"."ARTWORK" (ARTWORK_ID, COLLECTION_ID, MEDIUM_CODE, ARTWORK_TITLE, ARTWORK_DOC, LENGTH_CM, WIDTH_CM, 
    ART_STATUS, ART_ESTIMATED_VALUE) VALUES (ARTWORK_ID_SEQ.nextval, '1002', '4000', 'Foot', 
    TO_DATE('2000-06-11', 'YYYY-MM-DD'), '80', '1000', 'For Sale', '70000');




INSERT INTO "TAMOA"."SALE_TRANSACTION" (TRANSACTION_ID, CLIENT_ID, SALE_DATE, COMMISSION, VAT, DELIVERY_METHOD, SALES_TOTAL) 
    VALUES ('12001', '10000', TO_DATE('2019-05-07', 'YYYY-MM-DD'), '10000', '11200', 'Deliver', '80000');
INSERT INTO "TAMOA"."SALE_TRANSACTION" (TRANSACTION_ID, CLIENT_ID, SALE_DATE, COMMISSION, VAT, DELIVERY_METHOD, SALES_TOTAL) 
    VALUES (TRANSACTION_ID_SEQ.nextval, '10001', TO_DATE('2018-03-07', 'YYYY-MM-DD'), '10000', '11200', 'Pick Up', '80000');
INSERT INTO "TAMOA"."SALE_TRANSACTION" (TRANSACTION_ID, CLIENT_ID, SALE_DATE, COMMISSION, VAT, DELIVERY_METHOD, SALES_TOTAL) 
    VALUES (TRANSACTION_ID_SEQ.nextval, '10002', TO_DATE('2019-02-07', 'YYYY-MM-DD'), '10000', '11200', 'Storage', '80000');
INSERT INTO "TAMOA"."SALE_TRANSACTION" (TRANSACTION_ID, CLIENT_ID, SALE_DATE, COMMISSION, VAT, DELIVERY_METHOD, SALES_TOTAL) 
    VALUES (TRANSACTION_ID_SEQ.nextval, '10003', TO_DATE('2019-01-13', 'YYYY-MM-DD'), '10000', '11200', 'Ship', '80000');
INSERT INTO "TAMOA"."SALE_TRANSACTION" (TRANSACTION_ID, CLIENT_ID, SALE_DATE, COMMISSION, VAT, DELIVERY_METHOD, SALES_TOTAL) 
    VALUES (TRANSACTION_ID_SEQ.nextval, '10004', TO_DATE('2018-12-09', 'YYYY-MM-DD'), '10000', '11200', 'Ship International', '80000');



INSERT INTO "TAMOA"."SALE_TRANSACTION_DETAIL" (TRANSACTION_ID, ARTWORK_ID, SALES_PRICE) VALUES ('12000', '2000', '75000');
INSERT INTO "TAMOA"."SALE_TRANSACTION_DETAIL" (TRANSACTION_ID, ARTWORK_ID, SALES_PRICE) VALUES (TRANSACTION_ID_SEQ.nextval, '2001', '75000');
INSERT INTO "TAMOA"."SALE_TRANSACTION_DETAIL" (TRANSACTION_ID, ARTWORK_ID, SALES_PRICE) VALUES (TRANSACTION_ID_SEQ.nextval, '2002', '75000');
INSERT INTO "TAMOA"."SALE_TRANSACTION_DETAIL" (TRANSACTION_ID, ARTWORK_ID, SALES_PRICE) VALUES (TRANSACTION_ID_SEQ.nextval, '2003', '75000');




