--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "TAMOA"."CITY" 
   (	"CITY_CODE" NUMBER(6,0), 
	"CITY_NAME" VARCHAR2(30 BYTE), 
	"CITY_POSTAL_CODE" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
