--------------------------------------------------------
--  DDL for View FIND_CLIENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TAMOA"."FIND_CLIENTS" ("CLIENT_ID", "CITY_CODE", "CLIENT_INITS", "CLIENT_LNAME", "CLIENT_RSA_ID", "CLIENT_CELL", "CLIENT_EMAIL", "CLIENT_STREET_ADDRESS", "STREET_NR") AS 
  SELECT "CLIENT_ID","CITY_CODE","CLIENT_INITS","CLIENT_LNAME","CLIENT_RSA_ID","CLIENT_CELL","CLIENT_EMAIL","CLIENT_STREET_ADDRESS","STREET_NR"
FROM KLIENT WHERE client_lname LIKE '%'
;
