--------------------------------------------------------
--  Constraints for Table ART_MEDIUM
--------------------------------------------------------

  ALTER TABLE "TAMOA"."ART_MEDIUM" ADD CONSTRAINT "MEDIUM_DESCRIPTION_UK" UNIQUE ("MEDIUM_DESCRIPTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAMOA"."ART_MEDIUM" ADD CONSTRAINT "MEDIUM_CODE_PK" PRIMARY KEY ("MEDIUM_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAMOA"."ART_MEDIUM" MODIFY ("MEDIUM_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ART_MEDIUM" MODIFY ("MEDIUM_CODE" NOT NULL ENABLE);
