--------------------------------------------------------
--  Constraints for Table ARTIST
--------------------------------------------------------

  ALTER TABLE "TAMOA"."ARTIST" ADD CONSTRAINT "ARTIST_RSA_ID_UK" UNIQUE ("ARTIST_RSA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAMOA"."ARTIST" ADD CONSTRAINT "ARTIST_PK" PRIMARY KEY ("ARTIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAMOA"."ARTIST" MODIFY ("ARTIST_DOB" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTIST" MODIFY ("ARTIST_ACCOUNT_NO" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTIST" MODIFY ("ARTIST_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTIST" MODIFY ("ARTIST_CELL" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTIST" MODIFY ("ARTIST_RSA_ID" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTIST" MODIFY ("ARTIST_LNAME" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTIST" MODIFY ("ARTIST_INITS" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTIST" MODIFY ("BANK_CODE" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTIST" MODIFY ("ARTIST_ID" NOT NULL ENABLE);
