--------------------------------------------------------
--  Constraints for Table ARTWORK
--------------------------------------------------------

  ALTER TABLE "TAMOA"."ARTWORK" ADD CONSTRAINT "ARTWORK_ID_PK" PRIMARY KEY ("ARTWORK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAMOA"."ARTWORK" ADD CONSTRAINT "WIDTH_MIN" CHECK (Width_cm >0) ENABLE;
  ALTER TABLE "TAMOA"."ARTWORK" ADD CONSTRAINT "LENGTH_MIN" CHECK (Length_cm >0) ENABLE;
  ALTER TABLE "TAMOA"."ARTWORK" ADD CONSTRAINT "ARTWORK_ESTIMATED_VALUE_MIN" CHECK (Art_Estimated_Value >0) ENABLE;
  ALTER TABLE "TAMOA"."ARTWORK" MODIFY ("ART_ESTIMATED_VALUE" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTWORK" MODIFY ("ART_STATUS" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTWORK" MODIFY ("WIDTH_CM" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTWORK" MODIFY ("LENGTH_CM" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTWORK" MODIFY ("ARTWORK_DOC" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTWORK" MODIFY ("ARTWORK_TITLE" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTWORK" MODIFY ("MEDIUM_CODE" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTWORK" MODIFY ("COLLECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."ARTWORK" MODIFY ("ARTWORK_ID" NOT NULL ENABLE);
