--------------------------------------------------------
--  DDL for Table ARTWORK
--------------------------------------------------------

  CREATE TABLE "TAMOA"."ARTWORK" 
   (	"ARTWORK_ID" NUMBER(6,0), 
	"COLLECTION_ID" NUMBER(6,0), 
	"MEDIUM_CODE" NUMBER(6,0), 
	"ARTWORK_TITLE" VARCHAR2(50 BYTE), 
	"ARTWORK_DOC" DATE, 
	"LENGTH_CM" NUMBER(*,0), 
	"WIDTH_CM" NUMBER(*,0), 
	"ART_STATUS" VARCHAR2(10 BYTE), 
	"ART_ESTIMATED_VALUE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
