--------------------------------------------------------
--  Constraints for Table COLLECTION
--------------------------------------------------------

  ALTER TABLE "TAMOA"."COLLECTION" ADD CONSTRAINT "COLLECTION_ID_PK" PRIMARY KEY ("COLLECTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAMOA"."COLLECTION" MODIFY ("COLLECTION_NAME" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."COLLECTION" MODIFY ("ARTIST_ID" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."COLLECTION" MODIFY ("COLLECTION_ID" NOT NULL ENABLE);
