--------------------------------------------------------
--  Constraints for Table KLIENT
--------------------------------------------------------

  ALTER TABLE "TAMOA"."KLIENT" ADD CONSTRAINT "CLIENT_RSA_ID_UK" UNIQUE ("CLIENT_RSA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAMOA"."KLIENT" ADD CONSTRAINT "CLIENT_ID_PK" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAMOA"."KLIENT" MODIFY ("STREET_NR" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."KLIENT" MODIFY ("CLIENT_STREET_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."KLIENT" MODIFY ("CLIENT_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."KLIENT" MODIFY ("CLIENT_CELL" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."KLIENT" MODIFY ("CLIENT_RSA_ID" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."KLIENT" MODIFY ("CLIENT_LNAME" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."KLIENT" MODIFY ("CLIENT_INITS" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."KLIENT" MODIFY ("CITY_CODE" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."KLIENT" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
