--------------------------------------------------------
--  DDL for Table KLIENT
--------------------------------------------------------

  CREATE TABLE "TAMOA"."KLIENT" 
   (	"CLIENT_ID" NUMBER(6,0), 
	"CITY_CODE" NUMBER(6,0), 
	"CLIENT_INITS" VARCHAR2(6 BYTE), 
	"CLIENT_LNAME" VARCHAR2(30 BYTE), 
	"CLIENT_RSA_ID" VARCHAR2(13 BYTE), 
	"CLIENT_CELL" VARCHAR2(11 BYTE), 
	"CLIENT_EMAIL" VARCHAR2(30 BYTE), 
	"CLIENT_STREET_ADDRESS" VARCHAR2(35 BYTE), 
	"STREET_NR" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
