--------------------------------------------------------
--  Constraints for Table SALE_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TAMOA"."SALE_TRANSACTION" ADD CONSTRAINT "TRANSACTION_ID_PK" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAMOA"."SALE_TRANSACTION" ADD CONSTRAINT "SALE_TOTAL_CK" CHECK (Sales_Total > 0) ENABLE;
  ALTER TABLE "TAMOA"."SALE_TRANSACTION" MODIFY ("SALES_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."SALE_TRANSACTION" MODIFY ("DELIVERY_METHOD" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."SALE_TRANSACTION" MODIFY ("VAT" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."SALE_TRANSACTION" MODIFY ("COMMISSION" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."SALE_TRANSACTION" MODIFY ("SALE_DATE" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."SALE_TRANSACTION" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."SALE_TRANSACTION" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
