--------------------------------------------------------
--  DDL for Table SALE_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "TAMOA"."SALE_TRANSACTION" 
   (	"TRANSACTION_ID" NUMBER(8,0), 
	"CLIENT_ID" NUMBER(8,0), 
	"SALE_DATE" DATE, 
	"COMMISSION" NUMBER(8,2), 
	"VAT" NUMBER(8,2), 
	"DELIVERY_METHOD" VARCHAR2(20 BYTE), 
	"SALES_TOTAL" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
