--------------------------------------------------------
--  DDL for Table SALE_TRANSACTION_DETAIL
--------------------------------------------------------

  CREATE TABLE "TAMOA"."SALE_TRANSACTION_DETAIL" 
   (	"TRANSACTION_ID" NUMBER(6,0), 
	"ARTWORK_ID" NUMBER(6,0), 
	"SALES_PRICE" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
