--------------------------------------------------------
--  Ref Constraints for Table SALE_TRANSACTION_DETAIL
--------------------------------------------------------

  ALTER TABLE "TAMOA"."SALE_TRANSACTION_DETAIL" ADD CONSTRAINT "ARTWORK_ID_FK" FOREIGN KEY ("ARTWORK_ID")
	  REFERENCES "TAMOA"."ARTWORK" ("ARTWORK_ID") ENABLE;
  ALTER TABLE "TAMOA"."SALE_TRANSACTION_DETAIL" ADD CONSTRAINT "TRANSACTION_ID_FK" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TAMOA"."SALE_TRANSACTION" ("TRANSACTION_ID") ENABLE;
