--------------------------------------------------------
--  Constraints for Table SALE_TRANSACTION_DETAIL
--------------------------------------------------------

  ALTER TABLE "TAMOA"."SALE_TRANSACTION_DETAIL" ADD CONSTRAINT "SALE_TRANSACTION_DETAIL_PK" PRIMARY KEY ("TRANSACTION_ID", "ARTWORK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAMOA"."SALE_TRANSACTION_DETAIL" ADD CONSTRAINT "SALES_PRICE_MIN" CHECK (Sales_Price>0) ENABLE;
  ALTER TABLE "TAMOA"."SALE_TRANSACTION_DETAIL" MODIFY ("SALES_PRICE" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."SALE_TRANSACTION_DETAIL" MODIFY ("ARTWORK_ID" NOT NULL ENABLE);
  ALTER TABLE "TAMOA"."SALE_TRANSACTION_DETAIL" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
