--------------------------------------------------------
--  DDL for Table ARTIST
--------------------------------------------------------

  CREATE TABLE "TAMOA"."ARTIST" 
   (	"ARTIST_ID" NUMBER(6,0), 
	"BANK_CODE" NUMBER(6,0), 
	"ARTIST_INITS" VARCHAR2(6 BYTE), 
	"ARTIST_LNAME" VARCHAR2(30 BYTE), 
	"ARTIST_RSA_ID" VARCHAR2(13 BYTE), 
	"ARTIST_CELL" VARCHAR2(11 BYTE), 
	"ARTIST_EMAIL" VARCHAR2(30 BYTE), 
	"ARTIST_ACCOUNT_NO" VARCHAR2(15 BYTE), 
	"ARTIST_DOB" DATE, 
	"ARTIST_DOD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
